apiVersion: v1
data:
  application.properties: |-
        rutebanken.kubernetes.namespace={{.Values.env }}
        ukur.camel.tiamat.stop_place_quays.url=https4://storage.googleapis.com/anshar-production/mapping_data/stop_place_quays.json
        ukur.datastore.useDatastore=true
        # Temporary setting until bug in KeycloakWebSecurityConfigurerAdapter is fixed (The bean ''httpSessionManager'', defined in class path resource [xx/XXSecurityConfiguration.class], could not be registered. A bean with that name has already been defined in URL)
        spring.main.allow-bean-definition-overriding=true
        spring.main.web-application-type=none
        management.endpoints.web.exposure.include=info, health, prometheus
        management.endpoints.prometheus.enabled=true
        management.metrics.endpoint.export.prometheus.enabled=true
        debug=false
        entur.pubsub.subscriber.autocreate=false
        ukur.camel.pubsub.et=entur-google-pubsub://ukur.protobuf.estimated_timetables.subscription
        ukur.camel.pubsub.sx=entur-google-pubsub://ukur.protobuf.situation_exchange.subscription
        spring.cloud.gcp.pubsub.project-id={{ .Values.configmap.pubsub.project_id }}
        spring.cloud.gcp.pubsub.credentials.location={{ .Values.configmap.pubsub.credentials.path }}
kind: ConfigMap
metadata:
  name: {{ template "ukur.name" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | indent 4 }}
