apiVersion: v1
data:
  application.properties: |-
        rutebanken.kubernetes.namespace={{.Values.env }}
        ukur.camel.tiamat.stop_place_quays.url=http4://tiamat/services/stop_places/list/stop_place_quays/
        spring.activemq.pooled=true
        ukur.camel.anshar.receiver.baseurl=http://ukur/internal/
        ukur.camel.anshar.subscription=true
        spring.activemq.user=admin
        ukur.camel.anshar.url=http://anshar/anshar
        ukur.datastore.useDatastore=true
        spring.activemq.broker-url=tcp://activemq.default:61616
        # Temporary setting until bug in KeycloakWebSecurityConfigurerAdapter is fixed
        (The bean ''httpSessionManager'', defined in class path resource [xx/XXSecurityConfiguration.class],
        could not be registered. A bean with that name has already been defined in URL)
        spring.main.allow-bean-definition-overriding=true
        spring.main.web-application-type=none
        management.endpoints.web.exposure.include=info, health, prometheus
        management.endpoints.prometheus.enabled=true
        management.metrics.endpoint.export.prometheus.enabled=true
        debug=false
        ukur.camel.pubsub.et=entur-google-pubsub://protobuf.estimated_timetables
        ukur.camel.pubsub.sx=entur-google-pubsub://protobuf.situation_exchange
        spring.cloud.gcp.pubsub.project-id={{ .Values.configmap.pubsub.project_id }}
        spring.cloud.gcp.pubsub.credentials.location={{ .Values.configmap.pubsub.credentials.path }}
kind: ConfigMap
metadata:
  name: {{ template "ukur.name" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | indent 4 }}
