apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "ukur.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | indent 4 }}
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ template "ukur.name" . }}
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.rollingUpdate.maxUnavailable }}
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/path: /prometheus
        prometheus.io/port: '8080'
        prometheus.io/scrape: 'true'
      labels:
        {{- include "common.labels" . | indent 8 }}
    spec:
      containers:
        - env:
            - name: JAVA_OPTIONS
              value: -server -Xmx{{ .Values.resources.xmx }} -Dspring.config.additional-location=/etc/application-config/application.properties
                -Dfile.encoding=UTF-8
            - name: TZ
              value: Europe/Oslo
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/ukur-secret/ukur-service-account.json
            - name: SPRING_ACTIVEMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: ukur-activemq-password
          image: {{ .Values.image.identifier }}
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /internal/health/live
              port: {{ .Values.service.http.internalPort }}
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 60
          name: ukur
          ports:
            - containerPort: {{ .Values.service.http.internalPort }}
              name: http
              protocol: TCP
            - containerPort: 8778
              name: jolokia
              protocol: TCP
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /internal/health/ready
              port: {{ .Values.service.http.internalPort }}
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 60
          resources:
            limits:
              cpu: {{ .Values.resources.cpuLimit }}
              memory: {{ .Values.resources.memLimit }}
            requests:
              cpu: {{ .Values.resources.cpuRequest }}
              memory: {{ .Values.resources.memRequest }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/ukur-secret
              name: ukur-secret
            - mountPath: /etc/application-config
              name: application-config
              readOnly: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: rutebanken-registry-key
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
          - name: ukur-secret
            secret:
              defaultMode: 420
              secretName: ukur
          - configMap:
              defaultMode: 420
              name: ukur-config
            name: application-config