{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  labels:
    {{- include "common.labels" . | indent 4 }}
    traffic-type: api
  annotations:
    kubernetes.io/ingress.class: traefik
  name: realtime-deviations-v1
  namespace: {{ .Release.Namespace }}
spec:
  rules:
  - host: realtime-deviations-v1{{ .Values.ingress.domainName }}
    http:
      paths:
        - backend:
            serviceName: {{ template "ukur.name" . }}
            servicePort: {{ .Values.service.http.externalPort }}
{{- end }}