apiVersion: v1
data:
  application.properties: |-
        rutebanken.kubernetes.namespace={{ .Release.Namespace }}
        ukur.stop_place_quays.url=https://storage.cloud.google.com/ror-anshar-gcp2-prd/mapping_data/stop_place_quays.json
        ukur.stop_place_quays.interval=3600000
        ukur.datastore.useDatastore=true
        spring.main.web-application-type=none
        management.endpoints.web.exposure.include=info, health, prometheus
        management.endpoints.prometheus.enabled=true
        management.metrics.endpoint.export.prometheus.enabled=true
        debug=false
        entur.pubsub.subscriber.autocreate=false
        ukur.camel.pubsub.et=entur-google-pubsub://ukur.protobuf.estimated_timetables.subscription
        ukur.camel.pubsub.sx=entur-google-pubsub://ukur.protobuf.situation_exchange.subscription
        spring.cloud.gcp.pubsub.project-id={{ .Values.configmap.pubsub.project_id }}
        spring.profiles.active=gcp-datastore
        #logging.level.root=INFO
kind: ConfigMap
metadata:
  name: {{ template "ukur.name" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | indent 4 }}
