replicas: 3

env:
  datastore:
    project_id: entur-ror-prod

configmap:
  pubsub:
    project_id: entur-ror-prod

resources:
  cpuLimit: 7
  memLimit: 12000Mi
  cpuRequest: 1
  memRequest: 10000Mi
  xmx: 9000m

ingress:
  enabled: true
  loadBalancerIP: 35.205.233.237
  domainName: .entur.io

rbac:
  enabled: true