replicas: 2
env:
  datastore:
    project_id: entur-ror-dev
configmap:
  pubsub:
    project_id: entur-ror-dev

resources:
  cpuLimit: 7
  memLimit: 12000Mi
  cpuRequest: 1
  memRequest: 2000Mi
  xmx: 9000m

ingress:
  enabled: true
  domainName: .dev.entur.io

rbac:
  enabled: true