replicas: 2

configmap:
  pubsub:
    project_id: carbon-1287

resources:
  cpuLimit: 7
  memLimit: 12000Mi
  cpuRequest: 1
  memRequest: 2000Mi
  xmx: 9000m

ingress:
  enabled: true
  loadBalancerIP: 35.195.223.29
  domainName: -dev.dev.entur.io