replicas: 2

env:
  datastore:
    project_id: radon-1287

configmap:
  pubsub:
    project_id: radon-1287

resources:
  cpuLimit: 7
  memLimit: 12000Mi
  cpuRequest: 1
  memRequest: 2000Mi
  xmx: 9000m

ingress:
  enabled: true
  loadBalancerIP: 35.195.146.93
  domainName: -staging.staging.entur.io