replicas: 3

env:
  datastore:
    project_id: neon-1287

configmap:
  pubsub:
    project_id: neon-1287

resources:
  cpuLimit: 7
  memLimit: 12000Mi
  cpuRequest: 1
  memRequest: 10000Mi
  xmx: 9000m

ingress:
  enabled: true
  loadBalancerIP: 35.187.15.14
  domainName: -production.entur.io