replicas: 2
env:
  datastore:
    project_id: carbon-1287
configmap:
  pubsub:
    project_id: entur-ror-dev

resources:
  cpuLimit: 7
  memLimit: 12000Mi
  cpuRequest: 1
  memRequest: 2000Mi
  xmx: 9000m

ingress:
  enabled: true
  loadBalancerIP: 35.205.170.68
  domainName: .dev.entur.io

rbac:
  enabled: true