replicas: 2
env:
  datastore:
    project_id: ent-ukur-dev
configmap:
  pubsub:
    project_id: ent-ukur-dev
  loglevel: WARN

resources:
  memLimit: 12000Mi
  cpuRequest: 1
  memRequest: 2000Mi
  xmx: 9000m

ingress:
  enabled: true
  domainName: .dev.entur.io