replicas: 4

env:
  datastore:
    project_id: ent-ukur-prd

configmap:
  pubsub:
    project_id: ent-ukur-prd
  loglevel: INFO

resources:
  memLimit: 28000Mi
  cpuRequest: 5
  memRequest: 25000Mi
  xmx: 26000m

ingress:
  enabled: true
  domainName: .entur.io