replicas: 3

env:
  datastore:
    project_id: ent-ukur-prd

configmap:
  pubsub:
    project_id: ent-ukur-prd

resources:
  memLimit: 18000Mi
  cpuRequest: 4
  memRequest: 14000Mi
  xmx: 13000m

ingress:
  enabled: true
  domainName: .entur.io