replicas: 2

env:
  datastore:
    project_id: ent-ukur-tst

configmap:
  pubsub:
    project_id: ent-ukur-tst

resources:
  cpuLimit: 7
  memLimit: 12000Mi
  cpuRequest: 1
  memRequest: 2000Mi
  xmx: 9000m

ingress:
  enabled: true
  domainName: .staging.entur.io