apiVersion: v1
appVersion: "0.1.0"
description:
name: ukur
version: 0.1.0
keywords:
- ukur
sources:
- https://github.com/entur/ukur
maintainers:
- name: 'team-ror'
  email: team.rutedata@entur.org
engine: gotpl
