env: dev

replicas: 3


rollingUpdate:
  maxSurge: 1
  maxUnavailable: 1
image:
  identifier: ${artifact.metadata.image}
  imagePullPolicy: Always
resources:
  cpuLimit: 7
  memLimit: 12000Mi
  cpuRequest: 1
  memRequest: 10000Mi
  xmx: 9000m

configmap:
  pubsub:
    credentials:
      path: file:///etc/ukur-secret/ukur-service-account.json

service:
  http:
    externalPort: 80
    internalPort: 8080
ingress:
  enabled: true
  devIp: 35.195.223.29
  stagingIp: 35.195.146.93
  productionIp: 35.187.15.14