rollingUpdate:
  maxSurge: 1
  maxUnavailable: 1
image:
  identifier: ${artifact.metadata.image}
  imagePullPolicy: Always

configmap:
  pubsub:
    credentials:
      path: file:///etc/ukur-secret/ukur-service-account.json

service:
  http:
    externalPort: 80
    internalPort: 8080