rollingUpdate:
  maxSurge: 1
  maxUnavailable: 1
image:
  identifier: <+artifacts.primary.image>
  imagePullPolicy: Always

configmap:
  loglevel: INFO

service:
  http:
    externalPort: 80
    internalPort: 8080
